[profile.default]
fork_block_number = 20671003 
solc-version = "0.8.24"
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"  # Add this line
optimizer = true  # Optional: Enable the optimizer
optimizer_runs = 200  # Optional: Set optimizer runs

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/"
]

[fuzz]
seed = "0x2"

[invariant]
runs = 100
depth = 10
fail_on_revert = true



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
